import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { Alert, View } from "react-native";
import { RootStackParamList, UserProps } from "types";

import {
  BarcodeScanningResult,
  CameraView,
  useCameraPermissions,
} from "expo-camera";
import { useEffect, useState } from "react";
import { Text } from "react-native";
import Card from "src/component/card";
import { get } from "utils/access";
import Btn from "src/widgets/button";
import Header from "src/component/header";

type QRScannerScreenNavigationProp = NativeStackNavigationProp<
  RootStackParamList,
  "QRScanner"
>;

interface Props {
  navigation: QRScannerScreenNavigationProp;
}

export default function QRScanner({ navigation }: Props) {
  const [permission, requestPermission] = useCameraPermissions();
  const [student, setStudent] = useState<UserProps>();

  useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, []);

  const scannedResult = async ({ data }: BarcodeScanningResult) => {
    if (data) {
      const response = await get("/users/self", {
        token: data,
      });
      setStudent(response);
    }
  };

  return (
    <View className="w-full flex-1">
      <Header />
      <Card>
        <View className="w-full items-center">
          <Text
            style={{
              fontFamily: "LeagueGothic",
            }}
            className="text-3xl"
          >
            Attendance Scanner
          </Text>
          <Text>Scan the QR Code generated by the client</Text>
        </View>
        <CameraView
          style={{
            width: 200,
            height: 200,
            borderRadius: 5,
            overflow: "hidden",
            alignSelf: "center",
          }}
          facing="back"
          onBarcodeScanned={scannedResult}
        />
        <View className="w-full">
          <Text>Student ID: {student?.username}</Text>
          <Text>Name: {student?.last_name}, {student?.first_name} {student?.middle_name}</Text>
        </View>
        {student?.username ? <Btn>Test</Btn> : null}
      </Card>
    </View>
  );
}
