import { View } from "react-native";
import {
  BarcodeScanningResult,
  CameraView,
  useCameraPermissions,
} from "expo-camera";
import { useEffect, useState } from "react";
import { Text } from "react-native";
import Card from "src/component/card";
import { get_unauth, post_unauth } from "utils/access";
import Button from "src/widgets/button";
import Header from "src/component/header";
import { QRScannerProps } from "src/interfaces/navigation_props";
import { event_interface, UserProps } from "types";
import Input from "src/widgets/input";
import PageHeadings from "src/component/page_heading";
import { Snackbar } from "react-native-paper";

export default function QRScanner({ navigation }: QRScannerProps) {
  const [permission, requestPermission] = useCameraPermissions();
  const [student, setStudent] = useState<UserProps>();
  const [pleaseWait, setPleaseWait] = useState(false);
  const [eventID, setEventID] = useState("");
  const [eventInfo, setEventInfo] = useState<event_interface>();

  const [error, setError] = useState("");
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, []);

  useEffect(() => {
    setPleaseWait(false);
  }, [student]);

  const submitStudent = async () => {
    if (!pleaseWait) {
      setPleaseWait(true);
      const response = await post_unauth("participants", {
        event: eventID,
        participant: student?.username,
      });
      if (response.error) {
        setError(response.error);
        setVisible(true);
        setPleaseWait(false);
      } else {
        setError(response.message);
        setVisible(true);
        setStudent({});
      }
    }
  };

  const scannedResult = async ({ data }: BarcodeScanningResult) => {
    if (data && !pleaseWait) {
      setPleaseWait(true);
      const user_info = await get_unauth("users", {
        user: data,
      });
      if (user_info.error) {
        setError(user_info.error);
        setVisible(true);
      } else {
        setStudent(user_info);
      }
    }
  };

  const checkEvent = async () => {
    const response = await get_unauth("events", {
      key: eventID,
    });
    if (response.error) {
      setError(response.error);
      setVisible(true);
    }
    if (response.event_id) {
      setEventInfo(response);
      setError("Done");
      setVisible(true);
    }
  };

  return (
    <View className="w-full flex-1">
      <Header />
      {eventInfo ? (
        <Card>
          <View className="w-full items-center">
            <Text
              style={{
                fontFamily: "LeagueGothic",
              }}
              className="text-3xl"
            >
              Attendance Scanner
            </Text>
            <Text>Scan the QR Code generated by the client</Text>
          </View>
          <CameraView
            style={{
              width: 200,
              height: 200,
              borderRadius: 5,
              overflow: "hidden",
              alignSelf: "center",
            }}
            facing="back"
            onBarcodeScanned={scannedResult}
          />
          <View className="w-full">
            <Text>Student ID: {student?.username ?? "012A-3456"}</Text>
            <Text>
              Name: {student?.last_name ?? "Last name"},{" "}
              {student?.first_name ?? "First name"}{" "}
              {student?.middle_name ?? "Middle name"}
            </Text>
          </View>
          {student?.username ? (
            <Button onclick={submitStudent}>Present</Button>
          ) : null}
        </Card>
      ) : (
        <Card>
          <PageHeadings
            title="Organizer Verification"
            subtitle="Please enter the key of your event given by the event creator"
          />
          <View className="w-full items-center gap-4">
            <Input
              onchange={setEventID}
              label="Event Passcode"
              password={true}
            />
            <Button onclick={checkEvent}>Check passcode</Button>
          </View>
        </Card>
      )}
      <Snackbar
        visible={visible}
        onDismiss={() => setVisible(false)}
        action={{
          label: "Close",
          onPress: () => {
            setVisible(false);
          },
        }}
      >
        {error}
      </Snackbar>
    </View>
  );
}
